name: "NET"
info: "[Hello World, Team NIMIQ here!](https://youtu.be/3CzD3UQA9M4) - Start your journey in **Nimiq** checking out our [Introductory post](https://medium.com/nimiq-network/introducing-the-browser-based-blockchain-63d408add368) and [technical paper](https://medium.com/nimiq-network/nimiq-a-peer-to-peer-payment-protocol-native-to-the-web-ffd324bb084)."
contract: "0xcfb98637bcae43C13323EAa1731cED2B716962fD"
